import Link from 'next/link';

const DATA:any={
about:{eyebrow:'ABOUT MADAD',title:'Practical help, made easier to find.',intro:'MADAD is a community platform designed to help people share genuine needs, discover practical support and create meaningful connections safely.',sections:[['What we believe','Small acts of support can create real change. MADAD gives people a clear place to ask, offer and coordinate help across everyday needs.'],['What we do','We organize community needs into clear categories, make requests easier to understand and help contributors respond with context.'],['Our commitment','We are building a respectful, accessible and safety-conscious community where people remain in control of what they share.']]},
mission:{eyebrow:'OUR MISSION',title:'Turn everyday needs into practical action.',intro:'Our mission is to reduce the distance between someone needing help and someone able to offer it.',sections:[['Connect','Make relevant needs easier to discover.'],['Enable','Give people simple tools to ask for and offer practical help.'],['Protect','Promote respectful participation, reporting and safer community interactions.']]},
vision:{eyebrow:'OUR VISION',title:'A more connected world, one helpful action at a time.',intro:'We envision communities where asking for help is easier, offering help is more visible and meaningful support can begin with a simple conversation.',sections:[['Accessible support','Useful help should not be difficult to discover.'],['Human connection','Technology should make communities feel more connected, not less.'],['Responsible growth','Trust, safety and clarity must grow alongside the platform.']]},
goals:{eyebrow:'GOALS & AIMS',title:'Built around measurable, practical impact.',intro:'MADAD focuses on making community support easier to understand, safer to navigate and more useful in real life.',sections:[['Make needs visible','Present requests in clear categories with useful context.'],['Encourage responsible help','Support respectful communication and transparent expectations.'],['Strengthen trust','Provide reporting, moderation and clear community standards.'],['Improve continuously','Use feedback to refine the product, safety systems and user experience.']]},
how:{eyebrow:'HOW IT WORKS',title:'From one message to meaningful support.',intro:'MADAD keeps the process simple while giving each interaction enough context to be useful.',sections:[['1. Share a need','Create a clear request and choose the category that best fits it.'],['2. Get discovered','Community members can browse, search and filter requests.'],['3. Start a conversation','People who can help can respond and coordinate respectfully.'],['4. Stay responsible','Use reporting tools and follow community guidelines throughout the interaction.']]},
guidelines:{eyebrow:'COMMUNITY GUIDELINES',title:'A helpful community needs clear boundaries.',intro:'These standards apply to everyone using MADAD.',sections:[['Be respectful','Do not harass, threaten, discriminate against or humiliate others.'],['Be honest','Do not impersonate people or misrepresent a need, offer or identity.'],['Protect privacy','Do not publish private information without permission.'],['Keep requests appropriate','Do not use MADAD for unlawful, dangerous or exploitative activity.'],['Report concerns','If something appears unsafe or suspicious, use the reporting tools.']]},
safety:{eyebrow:'SAFETY & TRUST',title:'Help should never require ignoring your safety.',intro:'Use good judgment, protect your personal information and take extra care when moving conversations or meetings offline.',sections:[['Share less, not more','Only provide the personal details needed for a specific interaction.'],['Verify before acting','Independently verify important claims before sending money, documents or sensitive information.'],['Meet carefully','For offline exchanges, prefer appropriate public settings and involve trusted people when needed.'],['Report problems','Use platform reporting when behavior violates our rules or creates a safety concern.']]},
privacy:{eyebrow:'PRIVACY POLICY',title:'Privacy information, in plain language.',intro:'MADAD collects and processes information needed to operate accounts, provide platform features, improve reliability and protect the community.',sections:[['Information you provide','This can include account details and content you choose to submit.'],['How information is used','Information may be used to operate, secure and improve MADAD and respond to requests.'],['Your choices','You should avoid posting unnecessary sensitive information and can contact us regarding account-related requests.'],['Policy updates','This policy may change as the platform evolves. Material changes should be reflected on this page.']]},
terms:{eyebrow:'TERMS OF SERVICE',title:'Clear rules for using MADAD.',intro:'By using MADAD, you agree to use the platform responsibly and in accordance with applicable law and our community standards.',sections:[['Your account','You are responsible for information submitted through your account and for protecting account access.'],['Platform content','You must have the right to post content you submit and must not violate others’ rights.'],['No guaranteed outcome','MADAD helps people discover and coordinate support but cannot guarantee that any request will receive help.'],['Enforcement','Content or accounts may be restricted when required to protect users or enforce these terms.']]},
faq:{eyebrow:'HELP CENTER',title:'Answers that make MADAD easier to use.',intro:'A practical guide for sharing a need, offering help and using the community safely.',sections:[['How do I share a need?','Create an account, select the option to post a need, choose the most relevant category and explain your request clearly.'],['Who can respond to my post?','Community members can discover public requests and use available platform actions to offer help or start a respectful conversation.'],['How do I report something?','Use the Report action on relevant content and provide useful context. Reports can then be reviewed through the platform moderation workflow.'],['Is MADAD a guarantee of help?','No. MADAD helps people discover and coordinate practical support, but a successful outcome cannot be guaranteed.'],['How can I protect my privacy?','Share only information needed for the request. Avoid posting passwords, financial credentials, identity documents or other unnecessary sensitive information.']]},
contact:{eyebrow:'CONTACT & SUPPORT',title:'Questions, feedback or a safety concern?',intro:'We want MADAD to be useful and understandable. Contact us with product feedback, account questions or concerns about community activity.',sections:[['General support','Use the in-app reporting and account tools where available for the fastest context.'],['Safety concerns','If there is an immediate emergency, contact relevant local emergency services first.'],['Feedback','Tell us what works, what does not and what would make MADAD more useful.']]}
};
const mainLinks=[['Explore','/#feed'],['How it works','/how-it-works'],['Safety','/safety'],['About','/about'],['FAQ','/faq'],['Contact','/contact']];
const footerGroups=[{title:'Platform',links:[['Explore','/#feed'],['How it works','/how-it-works'],['Safety','/safety'],['Guidelines','/guidelines'],['Help center','/faq']]},{title:'MADAD',links:[['About','/about'],['Mission','/mission'],['Vision','/vision'],['Goals & aims','/goals']]},{title:'Legal',links:[['Privacy','/privacy'],['Terms','/terms'],['Contact','/contact']]}];
function Brand(){return <Link href="/" className="brand"><span>♥</span>MADAD</Link>}
function Footer(){return <footer className="mega-footer"><div className="footer-top"><div className="footer-brand"><Brand/><p>A more helpful world starts with one message.</p><small>Built for practical help and stronger communities.</small></div>{footerGroups.map(group=><div className="footer-column" key={group.title}><b>{group.title}</b>{group.links.map(([label,href])=><Link key={href} href={href}>{label}</Link>)}</div>)}<div className="footer-contact"><b>Find MADAD</b><span>Lahore, Pakistan</span><Link href="/contact">Contact & support →</Link><small>Contact details can be managed from the support page.</small></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} MADAD. Built around people.</span><span>A global community for practical help.</span></div></footer>}
export function InfoPage({page}:{page:keyof typeof DATA}){const d=DATA[page];return <main className="info-shell"><header className="info-header"><Brand/><nav>{mainLinks.map(([label,href])=><Link key={href} href={href}>{label}</Link>)}<Link className="header-cta" href="/#feed">Post a need</Link></nav></header><section className="info-hero"><p>{d.eyebrow}</p><h1>{d.title}</h1><div>{d.intro}</div><div className="info-actions"><Link href="/#feed">Explore the community</Link><Link href="/how-it-works">How MADAD works →</Link></div></section><section className="info-grid">{d.sections.map((s:[string,string],i:number)=><article key={i}><b>{String(i+1).padStart(2,'0')}</b><h2>{s[0]}</h2><p>{s[1]}</p></article>)}</section>{page==='contact'&&<section className="contact-panel"><div><span className="eyebrow">LOCATION & ACCESS</span><h2>Start with a message. Continue with the right support.</h2><p>MADAD is built for community access from Lahore, Pakistan and beyond. For product or safety questions, use the platform tools or the contact page.</p><div className="contact-details"><span><b>Location</b>Lahore, Pakistan</span><span><b>Support</b>Available through MADAD contact tools</span></div></div><div className="map-card"><iframe title="MADAD location" src="https://www.openstreetmap.org/export/embed.html?bbox=74.2%2C31.45%2C74.45%2C31.7&layer=mapnik" loading="lazy"/></div></section>}<section className="info-cta"><span className="eyebrow">READY TO TAKE PART?</span><h2>One useful connection can start with one message.</h2><Link href="/#feed">Return to MADAD →</Link></section><Footer/></main>}
